import Head from "next/head";
import Login from "../components/Login";
import { useUser } from "../context/UserContext";
import UserDashboard
  from "../components/UserDashboard";
export default function Home() {
  const { currUser } = useUser();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!currUser && <Login />}
      {currUser && <UserDashboard />}
    
    </>
  );
}
